exclude: '^docs/|/migrations/|devcontainer.json|templates/pages/profile_tabs/student_grades.html'
default_stages: [commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: 'templates/pages/profile_tabs/student_grades.html'
      - id: end-of-file-fixer
        exclude: 'templates/pages/profile_tabs/student_grades.html'
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.17.0'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '4.2']

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # Pre-commit breaks the graph rendering in this template
        exclude: 'templates/pages/profile_tabs/student_grades.html'
        exclude: 'templates/pages/profile_tabs/student_grades.html'
      # Formatter
      - id: ruff-format
        exclude: 'templates/pages/profile_tabs/student_grades.html'

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
        exclude: 'templates/pages/profile_tabs/student_grades.html'
      - id: djlint-django
        exclude: 'templates/pages/profile_tabs/student_grades.html'

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
