# Generated by Django 4.2.13 on 2024-05-17 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackPei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('feedback', models.TextField(verbose_name='Parecer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('NOT_START', 'Não iniciado'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Preenchidos'), ('FEEDBACK', 'Com parecer')], default='NOT_START', max_length=30)),
                ('objective', models.TextField(blank=True, verbose_name='Objetivos')),
                ('adapted_objective', models.TextField(blank=True, verbose_name='Objetivos Adaptados')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('adapted_content', models.TextField(blank=True, verbose_name='Conteúdo Adaptado')),
                ('methodology', models.TextField(blank=True, verbose_name='Metodologia')),
                ('adapted_methodology', models.TextField(blank=True, verbose_name='Metodologia Adaptada')),
                ('resources', models.TextField(blank=True, verbose_name='Recursos')),
                ('adapted_resources', models.TextField(blank=True, verbose_name='Recursos Adaptados')),
                ('assessments', models.TextField(blank=True, verbose_name='Avaliações')),
                ('adapted_assessments', models.TextField(blank=True, verbose_name='Avaliações Adaptadas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
