# Generated by Django 5.0.6 on 2024-07-27 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_enrollment_options'),
        ('educational_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pei',
            name='offer',
        ),
        migrations.AddField(
            model_name='pei',
            name='enrollment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='peis', to='academics.enrollment', verbose_name='Oferta'),
            preserve_default=False,
        ),
    ]
