# Generated by Django 4.2.13 on 2024-05-17 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educational_plan', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwser',
            new_name='Answer',
        ),
    ]
