# Generated by Django 5.0.6 on 2024-08-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_enrollment_yearsemesterreference_and_more'),
        ('educational_plan', '0002_remove_pei_offer_pei_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pei',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peis', to='academics.enrollment', verbose_name='Inscrição'),
        ),
    ]
