# Generated by Django 5.0.4 on 2024-10-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0003_alter_pei_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pei',
            name='status',
            field=models.CharField(choices=[('NOT_START', 'Não iniciado'), ('IN_PROGRESS', 'Em andamento'), ('FEEDBACK', 'Preenchido'), ('COMPLETED', 'Finalizado')], default='NOT_START', max_length=30),
        ),
    ]
