# Generated by Django 5.0.6 on 2024-07-19 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_subject_course_remove_subject_students_and_more'),
        ('educational_plan', '0003_rename_anwser_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pei',
            name='student',
        ),
        migrations.RemoveField(
            model_name='pei',
            name='subject',
        ),
        migrations.AddField(
            model_name='pei',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='peis', to='academics.offer', verbose_name='Oferta'),
        ),
    ]
