# Generated by Django 5.0.6 on 2024-07-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_studentgradesanual_created_by_and_more'),
        ('educational_plan', '0004_remove_pei_student_remove_pei_subject_pei_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pei',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peis', to='academics.offer', verbose_name='Oferta'),
        ),
    ]
