# Generated by Django 5.0.4 on 2024-10-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0004_alter_pei_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pei',
            name='academic_opinion_1',
            field=models.TextField(blank=True, verbose_name='Parecer do 1º Bimestre'),
        ),
        migrations.AddField(
            model_name='pei',
            name='academic_opinion_2',
            field=models.TextField(blank=True, verbose_name='Parecer do 2º Bimestre'),
        ),
        migrations.AddField(
            model_name='pei',
            name='academic_opinion_3',
            field=models.TextField(blank=True, verbose_name='Parecer do 3º Bimestre'),
        ),
        migrations.AddField(
            model_name='pei',
            name='academic_opinion_4',
            field=models.TextField(blank=True, verbose_name='Parecer do 4º Bimestre'),
        ),
        migrations.AddField(
            model_name='pei',
            name='academic_opinion_final',
            field=models.TextField(blank=True, verbose_name='Parecer do final'),
        ),
    ]
