# Generated by Django 5.0.6 on 2024-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0005_pei_academic_opinion_1_pei_academic_opinion_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pei',
            name='academic_opinion_final',
            field=models.TextField(blank=True, verbose_name='Parecer final'),
        ),
    ]
