# Generated by Django 5.0.4 on 2024-11-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0006_alter_pei_academic_opinion_final'),
        ('people', '0011_merge_20241020_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='pei',
            name='responsible_teacher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='Teachers', to='people.teacher', verbose_name='Professor Responsável'),
            preserve_default=False,
        ),
    ]
