# Generated by Django 5.0.4 on 2025-01-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0007_pei_responsible_teacher'),
        ('people', '0012_notification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pei',
            name='responsible_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Teachers', to='people.teacher', verbose_name='Professor Responsável'),
        ),
    ]
