# Generated by Django 5.0.4 on 2025-01-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0008_alter_pei_responsible_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pei',
            options={'ordering': ['id']},
        ),
    ]
