# Generated by Django 5.0.6 on 2025-02-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0009_alter_pei_options'),
        ('people', '0014_teacher_photoalt_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pei',
            name='responsible_teacher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='Teachers', to='people.teacher', verbose_name='Professor Responsável'),
            preserve_default=False,
        ),
    ]
