# Generated by Django 5.0.6 on 2025-07-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_plan', '0010_alter_pei_responsible_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pei',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='pei',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pei',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='pei',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='pei',
            name='resources',
        ),
    ]
