EDUCATIONAL_NECESSITIES_CHOICES = [
    ("Deficiência Visual - Cegueira Total", "Deficiência Visual - Cegueira Total"),
    ("Deficiência Visual - Baixa Visão", "Deficiência Visual - Baixa Visão"),
    ("Deficiência Intelectual Leve", "Deficiência Intelectual Leve"),
    ("Deficiência Intelectual Severa", "Deficiência Intelectual Severa"),
    ("Deficiência Física - Sequela Motora", "Deficiência Física - Sequela Motora"),
    ("Hidrocefalia", "Hidrocefalia"),
    ("TEA Nível 1 - Autismo", "TEA Nível 1 - Autismo"),
    ("TEA Nível 2 - Autismo", "TEA Nível 2 - Autismo"),
    ("TEA Nível 3 - Autismo", "TEA Nível 3 - Autismo"),
    ("DEFICIÊNCIA AUDITIVA - BAIXA AUDIÇÃO", "DEFICIÊNCIA AUDITIVA - BAIXA AUDIÇÃO"),
    ("DEFICIÊNCIA AUDITIVA - SURDEZ TOTAL", "DEFICIÊNCIA AUDITIVA - SURDEZ TOTAL"),
    (
        "DIFICULDADE DE SOCIALIZAÇÃO E APRENDIZAGEM",
        "DIFICULDADE DE SOCIALIZAÇÃO E APRENDIZAGEM",
    ),
    ("Transtorno Afetivo Bipolar", "Transtorno Afetivo Bipolar"),
    ("Ansiedade Generalizada", "Ansiedade Generalizada"),
    ("Obesidade", "Obesidade"),
    ("Mobilidade Reduzida", "Mobilidade Reduzida"),
    ("TDAH", "TDAH"),
    ("Ansiedade", "Ansiedade"),
]
