EDUCATIONAL_NECESSITIES_CHOICES = [
    "Deficiência Visual - Cegueira Total",
    "Deficiência Visual - Baixa Visão",
    "Deficiência Intelectual Leve",
    "Deficiência Intelectual Severa",
    "Deficiência Física - Sequela Motora",
    "Hidrocefalia",
    "TEA Nível 1 - Autismo",
    "TEA Nível 2 - Autismo",
    "TEA Nível 3 - Autismo",
    "DEFICIÊNCIA AUDITIVA - BAIXA AUDIÇÃO",
    "DEFICIÊNCIA AUDITIVA - SURDEZ TOTAL",
    "DIFICULDADE DE SOCIALIZAÇÃO E APRENDIZAGEM",
    "Transtorno Afetivo Bipolar",
    "Ansiedade Generalizada",
    "Obesidade",
    "Mobilidade Reduzida",
    "TDAH",
    "Ansiedade",
]
