# Generated by Django 5.0.6 on 2024-05-17 00:21

import django.db.models.deletion
import sistema_pei.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('course_type', models.CharField(choices=[('Técnico Integrado Regular', 'Técnico Integrado Regular'), ('Técnico Subsequente', 'Técnico Subsequente'), ('Curso Superior de Licenciatura', 'Curso Superior de Licenciatura'), ('Pós-Graduação', 'Pós-Graduação'), ('Técnico Integrado EJA', 'Técnico Integrado EJA'), ('Curso Superior de Tecnologia', 'Curso Superior de Tecnologia'), ('Engenharia', 'Engenharia'), ('Outros', 'Outros')], max_length=55, verbose_name='Tipo')),
                ('period', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=15, verbose_name='Turno')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=15, verbose_name='Períodos')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano referência')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.courses', verbose_name='Curso')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('students', models.ManyToManyField(related_name='subjects', to='people.student', verbose_name='Alunos')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='people.teacher', verbose_name='Professor')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
    ]
