# Generated by Django 5.0.6 on 2024-07-27 20:09

import django.core.validators
import sistema_pei.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
                ('grade3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='3 - Bimestre')),
                ('grade4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='4 - Bimestre')),
                ('year', models.IntegerField(verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Matrícula Anual',
                'verbose_name_plural': 'Matrículas Anuais',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], default='Aberta', max_length=50, verbose_name='Situação')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano referência')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('SEMESTER', 'Semestral'), ('YEAR', 'Anual')], max_length=15, verbose_name='Duração')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('course_type', models.CharField(choices=[('Técnico Integrado Regular', 'Técnico Integrado Regular'), ('Técnico Subsequente', 'Técnico Subsequente'), ('Curso Superior de Licenciatura', 'Curso Superior de Licenciatura'), ('Pós-Graduação', 'Pós-Graduação'), ('Técnico Integrado EJA', 'Técnico Integrado EJA'), ('Curso Superior de Tecnologia', 'Curso Superior de Tecnologia'), ('Engenharia', 'Engenharia'), ('Outros', 'Outros')], max_length=55, verbose_name='Tipo')),
                ('period', models.CharField(choices=[('MORNING', 'Matutino'), ('AFTERNOON', 'Vespertino'), ('NIGHT', 'Noturno')], max_length=15, verbose_name='Turno')),
                ('durationType', models.CharField(choices=[('SEMESTER', 'Semestral'), ('YEAR', 'Anual')], verbose_name='Tipo de duração')),
                ('number_of_periods', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de períodos/Anos')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
                ('semester', models.IntegerField(verbose_name='Semestre')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Matrícula Semestral',
                'verbose_name_plural': 'Matrículas Semestrais',
            },
        ),
    ]
