# Generated by Django 4.2.13 on 2024-05-17 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('course_type', models.CharField(choices=[('Técnico Integrado Regular', 'Técnico Integrado Regular'), ('Técnico Subsequente', 'Técnico Subsequente'), ('Curso Superior de Licenciatura', 'Curso Superior de Licenciatura'), ('Pós-Graduação', 'Pós-Graduação'), ('Técnico Integrado EJA', 'Técnico Integrado EJA'), ('Curso Superior de Tecnologia', 'Curso Superior de Tecnologia'), ('Engenharia', 'Engenharia'), ('Outros', 'Outros')], max_length=55, verbose_name='Tipo')),
                ('period', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=15, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=15, verbose_name='Períodos')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano referência')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
    ]
