# Generated by Django 5.0.6 on 2024-07-27 20:09

import django.db.models.deletion
import sistema_pei.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentsemester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='enrollmentsemester',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='enrollmentyearly',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='enrollmentyearly',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='enrollmentyearly',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='offer',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='people.teacher', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='enrollmentyearly',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.offer', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='enrollmentsemester',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.offer', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(related_name='subjects', to='academics.course', verbose_name='Cursos'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='academics.subject', verbose_name='Disciplina'),
        ),
    ]
