# Generated by Django 5.0.6 on 2024-07-19 14:51

import django.db.models.deletion
import sistema_pei.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('people', '0003_alter_specificnecessitie_name_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('SEMESTER', 'Semestral'), ('YEAR', 'Anual')], max_length=15, verbose_name='Duração'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('course_type', models.CharField(choices=[('Técnico Integrado Regular', 'Técnico Integrado Regular'), ('Técnico Subsequente', 'Técnico Subsequente'), ('Curso Superior de Licenciatura', 'Curso Superior de Licenciatura'), ('Pós-Graduação', 'Pós-Graduação'), ('Técnico Integrado EJA', 'Técnico Integrado EJA'), ('Curso Superior de Tecnologia', 'Curso Superior de Tecnologia'), ('Engenharia', 'Engenharia'), ('Outros', 'Outros')], max_length=55, verbose_name='Tipo')),
                ('period', models.CharField(choices=[('MORNING', 'Matutino'), ('AFTERNOON', 'Vespertino'), ('NIGHT', 'Noturno')], max_length=15, verbose_name='Turno')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(related_name='subjects', to='academics.course', verbose_name='Cursos'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], default='Aberta', max_length=50, verbose_name='Situação')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano referência')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='academics.subject', verbose_name='Disciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='people.teacher', verbose_name='Professor')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grade_1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota 1')),
                ('grade_2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota 2')),
                ('grade_3', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota 3')),
                ('grade_4', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota 4')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.student', verbose_name='Aluno')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.offer', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('offer', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
