# Generated by Django 5.0.6 on 2024-07-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_enrollmentyearly_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
    ]
