# Generated by Django 5.0.6 on 2024-07-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentgrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrades',
            name='grade1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 1'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grade2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 2'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grade3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 3'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='grade4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota 4'),
        ),
    ]
