# Generated by Django 5.0.6 on 2024-08-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_enrollment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='YearSemesterReference',
            field=models.IntegerField(default=1, verbose_name='Semestre/Ano de referencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.offer', verbose_name='Oferta'),
        ),
    ]
