# Generated by Django 5.0.6 on 2024-07-18 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_studentgrades_grade1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrades',
            name='grade2',
        ),
        migrations.RemoveField(
            model_name='studentgrades',
            name='grade4',
        ),
        migrations.RemoveField(
            model_name='studentgrades',
            name='grade1',
        ),
        migrations.RemoveField(
            model_name='studentgrades',
            name='grade3',
        ),
        migrations.CreateModel(
            name='StudentGradesSemestral',
            fields=[
                ('studentgrades_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academics.studentgrades')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
            ],
            options={
                'abstract': False,
            },
            bases=('academics.studentgrades',),
        ),
        migrations.CreateModel(
            name='StudentGradesAnual',
            fields=[
                ('studentgrades_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academics.studentgrades')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
                ('grade3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='3 - Bimestre')),
                ('grade4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='4 - Bimestre')),
            ],
            options={
                'abstract': False,
            },
            bases=('academics.studentgrades',),
        ),
    ]
