# Generated by Django 5.0.6 on 2024-08-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_enrollment_yearsemesterreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.course', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='YearSemesterReference',
            field=models.IntegerField(verbose_name='Semestre/Ano de referência'),
        ),
    ]
