# Generated by Django 5.0.6 on 2024-07-18 03:13

import django.db.models.deletion
import sistema_pei.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_studentgrades_grade1_and_more'),
        ('people', '0017_responsible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGradesAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
                ('grade3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='3 - Bimestre')),
                ('grade4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='4 - Bimestre')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student', verbose_name='Aluno')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject', verbose_name='Matéria')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Nota Anual',
                'verbose_name_plural': 'Notas Anuais',
            },
        ),
        migrations.CreateModel(
            name='StudentGradesSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student', verbose_name='Aluno')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject', verbose_name='Matéria')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Nota Semestral',
                'verbose_name_plural': 'Notas Semestrais',
            },
        ),
        migrations.DeleteModel(
            name='StudentGrades',
        ),
    ]
