# Generated by Django 5.0.6 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_enrollment_yearsemesterreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='YearSemesterReference',
            field=models.IntegerField(verbose_name='Semestre/Ano de referência'),
        ),
    ]
