# Generated by Django 5.0.6 on 2024-07-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentgradesanual_studentgradessemestral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='durationType',
            field=models.CharField(choices=[('SEMESTER', 'Semestral'), ('YEAR', 'Anual')], default='a', verbose_name='Tipo de duração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgradesanual',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgradessemestral',
            name='semester',
            field=models.IntegerField(default=1, verbose_name='Semestre'),
            preserve_default=False,
        ),
    ]
