# Generated by Django 5.0.6 on 2024-09-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_enrollment_yearsemesterreference'),
        ('academics', '0006_offer_course_alter_enrollment_yearsemesterreference'),
    ]

    operations = [
    ]
