# Generated by Django 5.0.4 on 2024-09-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_enrollment_yearsemesterreference'),
        ('academics', '0006_offer_course_alter_enrollment_yearsemesterreference'),
    ]

    operations = [
    ]
