# Generated by Django 5.0.6 on 2024-07-20 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courses_durationtype_studentgradesanual_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='number_of_periods',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de períodos/Anos'),
        ),
    ]
