# Generated by Django 5.0.4 on 2024-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_merge_20240909_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], default=1, verbose_name='Semestre referência'),
            preserve_default=False,
        ),
    ]
