# Generated by Django 5.0.6 on 2024-09-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_merge_20240906_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='durationType',
            new_name='duration_type',
        ),
    ]
