# Generated by Django 5.0.6 on 2024-07-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_subject_course_remove_subject_students_and_more'),
        ('academics', '0008_alter_courses_number_of_periods'),
    ]

    operations = [
    ]
