# Generated by Django 5.0.6 on 2024-09-10 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_rename_durationtype_course_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_periods',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de períodos/Anos'),
        ),
    ]
