# Generated by Django 5.0.6 on 2024-07-27 15:51

import django.core.validators
import django.db.models.deletion
import sistema_pei.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_merge_20240727_1250'),
        ('people', '0017_responsible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgradesanual',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentgradesanual',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentgradesanual',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentgradesanual',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='studentgradessemestral',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentgradessemestral',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentgradessemestral',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentgradessemestral',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='course',
            name='durationType',
            field=models.CharField(choices=[('SEMESTER', 'Semestral'), ('YEAR', 'Anual')], default='SEMESTER', verbose_name='Tipo de duração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_periods',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de períodos/Anos'),
        ),
        migrations.CreateModel(
            name='EnrollmentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
                ('semester', models.IntegerField(verbose_name='Semestre')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.offer', verbose_name='Oferta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student', verbose_name='Aluno')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Matrícula Semestral',
                'verbose_name_plural': 'Matrículas Semestrais',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grade1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1 - Bimestre')),
                ('grade2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='2 - Bimestre')),
                ('grade3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='3 - Bimestre')),
                ('grade4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='4 - Bimestre')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.offer', verbose_name='Oferta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student', verbose_name='Aluno')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Matrícula Anual',
                'verbose_name_plural': 'Matrículas Anuais',
            },
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='StudentGradesAnual',
        ),
        migrations.DeleteModel(
            name='StudentGradesSemestral',
        ),
    ]
