# Generated by Django 5.0.4 on 2024-09-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_offer_semester'),
        ('academics', '0009_alter_course_number_of_periods'),
    ]

    operations = [
    ]
