# Generated by Django 5.0.4 on 2024-10-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_merge_20240914_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assessments',
            field=models.TextField(blank=True, verbose_name='Avaliações'),
        ),
        migrations.AddField(
            model_name='subject',
            name='content',
            field=models.TextField(blank=True, verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='subject',
            name='methodology',
            field=models.TextField(blank=True, verbose_name='Metodologia'),
        ),
        migrations.AddField(
            model_name='subject',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Objetivos'),
        ),
        migrations.AddField(
            model_name='subject',
            name='resources',
            field=models.TextField(blank=True, verbose_name='Recursos'),
        ),
    ]
