# Generated by Django 5.0.4 on 2024-11-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subject_assessments_subject_content_and_more'),
        ('people', '0011_merge_20241020_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='teacher',
        ),
        migrations.AddField(
            model_name='offer',
            name='teachers',
            field=models.ManyToManyField(related_name='offers', to='people.teacher', verbose_name='Professor'),
        ),
    ]
