# Generated by Django 5.0.6 on 2025-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_offer_teacher_offer_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='YearSemesterReference',
            field=models.IntegerField(verbose_name='Cursado no semestre/ano do curso'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], verbose_name='Semestre referência do período letivo'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Ano referência do período letivo'),
        ),
    ]
