# Generated by Django 5.0.6 on 2025-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_enrollment_yearsemesterreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='absences1',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas 1 Bimestre'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='absences2',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas 2 Bimestre'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='absences3',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas 3 Bimestre'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='absences4',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas 4 Bimestre'),
        ),
    ]
