# Generated by Django 5.0.6 on 2025-03-21 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_enrollment_absences1_enrollment_absences2_and_more'),
        ('people', '0016_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Sincronização')),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('PARTIAL', 'Parcialmente Completo'), ('PENDING', 'Pendente')], default='PENDING', max_length=10, verbose_name='Status')),
                ('error_details', models.JSONField(blank=True, null=True, verbose_name='Detalhes dos erros')),
                ('enrollments', models.ManyToManyField(blank=True, related_name='sync_logs', to='academics.enrollment', verbose_name='Matrículas sincronizadas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='people.student', verbose_name='Discente')),
            ],
        ),
    ]
