# Generated by Django 5.0.6 on 2025-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_synchronizationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização'),
        ),
        migrations.DeleteModel(
            name='SynchronizationLog',
        ),
    ]
