# Generated by Django 5.0.6 on 2025-07-21 12:42

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_enrollment_last_synced_at_delete_synchronizationlog'),
    ]

    operations = [
        UnaccentExtension()
    ]
