# Generated by Django 5.0.6 on 2025-09-01 17:21

import django.core.validators
import django.db.models.deletion
import sistema_pei.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_auto_20250721_0942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Código da matriz')),
                ('description', models.CharField(verbose_name='Descrição da matriz')),
                ('year', models.IntegerField(verbose_name='Ano da matriz')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Matriz',
                'verbose_name_plural': 'Matrizes',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.matrix', verbose_name='Matriz da disciplina'),
        ),
    ]
