# Generated by Django 4.2.13 on 2024-05-17 13:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('NEWS', 'News'), ('ALERT', 'Alert'), ('FAIL', 'Fail')], max_length=50, verbose_name='Notification Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='SpecificNecessitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(choices=[('Deficiência Visual - Cegueira Total', 'Deficiência Visual - Cegueira Total'), ('Deficiência Visual - Baixa Visão', 'Deficiência Visual - Baixa Visão'), ('Deficiência Intelectual Leve', 'Deficiência Intelectual Leve'), ('Deficiência Intelectual Severa', 'Deficiência Intelectual Severa'), ('Deficiência Física - Sequela Motora', 'Deficiência Física - Sequela Motora'), ('Hidrocefalia', 'Hidrocefalia'), ('TEA Nível 1 - Autismo', 'TEA Nível 1 - Autismo'), ('TEA Nível 2 - Autismo', 'TEA Nível 2 - Autismo'), ('TEA Nível 3 - Autismo', 'TEA Nível 3 - Autismo'), ('DEFICIÊNCIA AUDITIVA - BAIXA AUDIÇÃO', 'DEFICIÊNCIA AUDITIVA - BAIXA AUDIÇÃO'), ('DEFICIÊNCIA AUDITIVA - SURDEZ TOTAL', 'DEFICIÊNCIA AUDITIVA - SURDEZ TOTAL'), ('DIFICULDADE DE SOCIALIZAÇÃO E APRENDIZAGEM', 'DIFICULDADE DE SOCIALIZAÇÃO E APRENDIZAGEM'), ('Transtorno Afetivo Bipolar', 'Transtorno Afetivo Bipolar'), ('Ansiedade Generalizada', 'Ansiedade Generalizada'), ('Obesidade', 'Obesidade'), ('Mobilidade Reduzida', 'Mobilidade Reduzida'), ('TDAH', 'TDAH'), ('Ansiedade', 'Ansiedade')], max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Necessidade Específica',
                'verbose_name_plural': 'Necessidades Específicas',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('serie', models.PositiveSmallIntegerField(choices=[(1, '1° Ano'), (2, '2° Ano'), (3, '3° Ano'), (4, '4° Ano')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Série')),
                ('registration', models.CharField(blank=True, max_length=50, verbose_name='Matrícula')),
                ('personal_history', models.TextField(verbose_name='Histórico')),
                ('image', models.ImageField(upload_to='students', verbose_name='Foto')),
                ('general_necessitie', models.TextField(verbose_name='Outras necessidades educacionais específicas do(a) estudante')),
                ('creation_reasons', models.TextField(verbose_name='Motivos para a criação do PEI/ Adaptações')),
                ('abilities', models.TextField(verbose_name='Conhecimentos, Habilidades,Capacidades e Interesses')),
                ('dificulties', models.TextField(verbose_name='Dificuldades')),
                ('specific_necessities', models.TextField(verbose_name='Necessidades específicas')),
            ],
            options={
                'verbose_name': 'Discente',
                'verbose_name_plural': 'Discentes',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
