# Generated by Django 5.0.6 on 2024-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificnecessitie',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
