# Generated by Django 5.0.6 on 2024-06-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_specificnecessitie_name_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
