# Generated by Django 5.0.6 on 2024-09-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto'),
        ),
    ]
