# Generated by Django 5.0.6 on 2024-06-26 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_sector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.sector', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.sector', verbose_name='Setor'),
        ),
    ]
