# Generated by Django 5.0.4 on 2024-10-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sectors',
        ),
    ]
