# Generated by Django 5.0.6 on 2024-06-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_student_sector_teacher_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sector',
        ),
    ]
