# Generated by Django 5.0.4 on 2024-10-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_student_sectors'),
        ('users', '0006_alter_user_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sectors',
            field=models.ManyToManyField(to='users.sector', verbose_name='Setores'),
        ),
    ]
