# Generated by Django 5.0.4 on 2024-10-10 01:37

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_student_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sectors',
        ),
        migrations.AddField(
            model_name='student',
            name='sectors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NAPNE', 'NAPNE'), ('ETEP', 'ETEP'), ('DIAC', 'DIAC')], default='NAPNE', max_length=15, verbose_name='Setores'),
            preserve_default=False,
        ),
    ]
