# Generated by Django 5.0.6 on 2024-06-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_remove_sector_created_at_remove_sector_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='sector',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
