# Generated by Django 5.0.6 on 2024-07-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('people', '0007_remove_responsible_sector_delete_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.courses', verbose_name='Curso'),
            preserve_default=False,
        ),
    ]
