# Generated by Django 5.0.4 on 2024-10-10 01:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_remove_student_sectors_student_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sectors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NAPNE', 'NAPNE'), ('ETEP', 'ETEP'), ('DIAC', 'DIAC')], max_length=15, verbose_name='Setores'),
        ),
    ]
