# Generated by Django 5.0.6 on 2024-07-09 17:54

import django.db.models.deletion
import sistema_pei.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_remove_responsible_sector_delete_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='teachers', verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='Abreviação')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(sistema_pei.core.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='people.campus', verbose_name='Campus'),
        ),
    ]
