# Generated by Django 5.0.4 on 2024-10-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_student_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='abilities',
            field=models.TextField(blank=True, verbose_name='Conhecimentos, Habilidades, Capacidades e Interesses'),
        ),
    ]
