# Generated by Django 5.0.6 on 2024-07-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reference_period',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Período de Referência'),
            preserve_default=False,
        ),
    ]
