# Generated by Django 5.0.6 on 2024-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_teacher_matricula_teacher_photo_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='abbreviation',
            field=models.CharField(max_length=4, unique=True, verbose_name='Abreviação'),
        ),
    ]
