# Generated by Django 5.0.6 on 2024-07-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_campus_abbreviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='matricula',
            new_name='code',
        ),
    ]
