# Generated by Django 5.0.6 on 2024-07-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_student_reference_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='serie',
        ),
    ]
