# Generated by Django 5.0.6 on 2024-10-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_assistant_is_pedagogue_assistant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
