# Generated by Django 5.0.6 on 2024-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_rename_matricula_teacher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Matrícula'),
        ),
    ]
