# Generated by Django 5.0.6 on 2024-10-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_student_abilities'),
        ('people', '0010_remove_coordinator_campus_and_more'),
    ]

    operations = [
    ]
