# Generated by Django 5.0.4 on 2024-12-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_merge_20241020_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Link de ação ao clicar'),
        ),
    ]
