# Generated by Django 5.0.6 on 2024-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_studentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='abilities',
            field=models.TextField(blank=True, verbose_name='Conhecimentos, Habilidades,Capacidades e Interesses'),
        ),
        migrations.AlterField(
            model_name='student',
            name='creation_reasons',
            field=models.TextField(blank=True, verbose_name='Motivos para a criação do PEI/ Adaptações'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dificulties',
            field=models.TextField(blank=True, verbose_name='Dificuldades'),
        ),
        migrations.AlterField(
            model_name='student',
            name='general_necessitie',
            field=models.TextField(blank=True, verbose_name='Outras necessidades educacionais específicas do(a) estudante'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specific_necessities',
            field=models.TextField(blank=True, verbose_name='Necessidades específicas'),
        ),
    ]
