# Generated by Django 5.0.6 on 2024-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_student_abilities_and_more'),
        ('users', '0002_sector_user_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='users.sector', verbose_name='Setores'),
        ),
    ]
