# Generated by Django 5.0.4 on 2025-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_notification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teachers', verbose_name='Foto'),
        ),
    ]
