# Generated by Django 5.0.6 on 2024-07-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_student_sectors'),
        ('users', '0002_sector_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sectors',
            field=models.ManyToManyField(to='users.sector', verbose_name='Setores'),
        ),
    ]
