# Generated by Django 5.0.4 on 2025-01-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photoAlt',
            field=models.ImageField(blank=True, null=True, upload_to='teachers', verbose_name='Foto alternativa'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto'),
        ),
    ]
