# Generated by Django 5.0.6 on 2024-07-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_alter_student_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='responsible_person',
        ),
        migrations.DeleteModel(
            name='Responsible',
        ),
    ]
