# Generated by Django 5.0.6 on 2024-07-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_teacher_code'),
        ('people', '0015_remove_student_responsible_person_delete_responsible'),
    ]

    operations = [
    ]
