# Generated by Django 5.0.6 on 2025-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem do alerta')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta Global',
                'verbose_name_plural': 'Alertas Globais',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
