# Generated by Django 5.0.6 on 2024-07-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_studentgradesanual_created_by_and_more'),
        ('people', '0017_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.course', verbose_name='Curso'),
        ),
    ]
