# Generated by Django 5.0.6 on 2025-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_alertaglobal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertaglobal',
            options={},
        ),
        migrations.AddField(
            model_name='alertaglobal',
            name='cor_base',
            field=models.CharField(choices=[('yellow', 'Amarelo'), ('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('gray', 'Cinza')], default='yellow', max_length=20, verbose_name='Cor base'),
        ),
    ]
