from django.urls import path

from sistema_pei.academics import views

app_name = "academics"
urlpatterns = [
    path("dashboard/", views.AcademicsIndexView.as_view(), name="dashboard"),
    path(
        "course/list/",
        views.CourseListView.as_view(),
        name="course_list",
    ),
    path(
        "course/create/",
        views.CourseCreateView.as_view(),
        name="course_create",
    ),
    path(
        "course/update/<int:pk>/",
        views.CourseUpdateView.as_view(),
        name="course_update",
    ),
    path(
        "course/delete/<int:pk>/",
        views.CourseDeleteView.as_view(),
        name="course_delete",
    ),
    path(
        "course/detail/<int:pk>/",
        views.CourseDetailView.as_view(),
        name="course_detail",
    ),
    path(
        "subjects/list/",
        views.SubjectsPageView.as_view(),
        name="subject_list",
    ),
    path(
        "subjects/create/",
        views.CreateSubjectPageView.as_view(),
        name="subject_create",
    ),
    path(
        "subjects/update/<int:pk>",
        views.EditSubjectPageView.as_view(),
        name="subject_update",
    ),
    path(
        "subjects/delete/<int:pk>",
        views.SubjectDeleteView.as_view(),
        name="subject_delete",
    ),
    path(
        "subjects/remove_student_from_subject/<int:subject_id>/<int:student_id>",
        views.RemoveStudentFromSubjectView.as_view(),
        name="remove_student_from_subject",
    ),
    path(
        "subjects/detail/<int:pk>/",
        views.SubjectDetailView.as_view(),
        name="subject_detail",
    ),
    path(
        "offers/list/",
        views.OfferListView.as_view(),
        name="offer_list",
    ),
    path(
        "offers/create/",
        views.OfferCreateView.as_view(),
        name="offer_create",
    ),
    path(
        "offers/update/<int:pk>/",
        views.OfferUpdateView.as_view(),
        name="offer_update",
    ),
    path(
        "offers/delete/<int:pk>/",
        views.OfferDeleteView.as_view(),
        name="offer_delete",
    ),
    path(
        "offers/detail/<int:pk>/",
        views.OfferDetailView.as_view(),
        name="offer_detail",
    ),
    path(
        "offers/remove_student_from_offer/<int:offer_id>/<int:student_id>/",
        views.RemoveStudentFromOfferView.as_view(),
        name="remove_student_from_offer",
    ),
    path(
        "offers/add_student_to_offer/<int:pk>/",
        views.AddStudentToOfferView.as_view(),
        name="add_student_to_offer",
    ),
    path(
        "offers/get_subjects_by_course_id/<int:pk>/",
        views.GetSubjectsByCourseView.as_view(),
        name="get_subjects_by_course",
    ),
]
