# Generated by Django 5.0.6 on 2025-07-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('releaseDate', models.DateTimeField()),
            ],
            options={
                'ordering': ['-releaseDate'],
            },
        ),
    ]
