# Generated by Django 5.0.6 on 2025-07-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peis_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-releaseDate'], 'verbose_name': 'Versão do App', 'verbose_name_plural': 'Versões do App'},
        ),
        migrations.AddField(
            model_name='appversion',
            name='apkFile',
            field=models.FileField(blank=True, upload_to='app-apks/'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='releaseDate',
            field=models.DateTimeField(verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Versão'),
        ),
    ]
