# Generated by Django 5.0.6 on 2025-08-01 14:46

import django.core.validators
import sistema_pei.peis_sync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peis_sync', '0002_alter_appversion_options_appversion_apkfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='apkFile',
            field=models.FileField(blank=True, upload_to=sistema_pei.peis_sync.models.apk_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])], verbose_name='Arquivo de instalação APK'),
        ),
    ]
