URL_LENGTH = 500
MAX_CHAR_FIELD_NAME_LENGTH = 255
MEDIUM_CHAR_FIELD_NAME_LENGTH = 100
SMALL_CHAR_FIELD_NAME_LENGTH = 50
PUBLIC_STRING = "PUBLIC"
PRIVATE_STRING = "PRIVATE"
DEFAULT_PAGE_SIZE = 10

SUAP_VALIDATION_URL = "https://suap.ifrn.edu.br/api/token/verify"
STATUS_CODE_OK = 200
