# Generated by Django 5.0.6 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sector_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(choices=[('NAPNE', 'NAPNE')], default=1, max_length=50, verbose_name='Setor'),
            preserve_default=False,
        ),
    ]
