# Generated by Django 5.0.6 on 2024-09-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, choices=[('NAPNE', 'NAPNE'), ('ETEP', 'ETEP')], max_length=50, verbose_name='Setor'),
        ),
    ]
