# Generated by Django 5.0.6 on 2024-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, choices=[('NAPNE', 'NAPNE'), ('ETEP', 'ETEP'), ('DIAC', 'DIAC')], max_length=50, verbose_name='Setor'),
        ),
    ]
