# Generated by Django 5.0.4 on 2024-10-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_remove_student_sectors_student_sectors'),
        ('users', '0006_alter_user_sector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
