# Generated by Django 5.0.8 on 2024-10-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, max_length=500, verbose_name='Foto'),
        ),
    ]
