#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py load_db_data

python /app/manage.py collectstatic --noinput --disable-collectfast

exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
