name: CICD - Deploy em Develop

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
        known_hosts: |
          ${{ secrets.KNOWN_HOSTS_DEV }}  # Current server
        if_key_exists: replace
    - name: Deploy to host
      run: ${{ vars.SSH_CMD_DEV }} ${{ vars.DEPLOY_CMD_DEV }}
